# Generated by Django 5.0.3 on 2024-03-14 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=100)),
                ('inteiro', models.IntegerField()),
                ('booleano', models.BooleanField()),
                ('opcaoSelect', models.CharField(max_length=100)),
                ('opcaoRadio', models.CharField(max_length=100)),
            ],
        ),
    ]
