# Generated by Django 5.0.3 on 2024-03-15 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_doador', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Formulario',
        ),
    ]
