# Generated by Django 4.2.13 on 2024-05-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doador', '0002_rename_doador_doacao_codigo_doador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doador',
            name='situacao',
            field=models.TextField(default='ativo'),
        ),
    ]
