# Generated by Django 5.0.4 on 2024-04-18 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doador', '0002_rename_usuarios_formulario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('volume', models.DecimalField(decimal_places=3, max_digits=10)),
                ('situacao', models.TextField()),
            ],
            options={
                'db_table': 'doacao',
            },
        ),
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('cpf', models.TextField()),
                ('contato', models.TextField()),
                ('tipo_sanguineo', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2)),
                ('rh', models.CharField(choices=[('Positivo', 'Positivo'), ('Negativo', 'Negativo')], max_length=8)),
                ('tipo_rh_corretos', models.BooleanField()),
                ('situacao', models.TextField()),
            ],
            options={
                'db_table': 'doador',
            },
        ),
        migrations.DeleteModel(
            name='Formulario',
        ),
        migrations.AddField(
            model_name='doacao',
            name='doador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_doador.doador'),
        ),
    ]
