# Generated by Django 5.0.2 on 2024-04-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doador', '0004_remove_doacao_situacao_remove_doador_situacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doador',
            name='tipo_rh_corretos',
            field=models.BooleanField(default=False),
        ),
    ]
